siteName: Tergar Česko
siteDescription: Česká pobočka mezinárodní meditační komunity Tergar pod vedením Yongey Mingyur Rinpočheho. Kurzy, skupiny, akce a zdroje pro meditaci v ČR.
contactEmail: czech@tergar.org
donationUrl: https://darujme.cz/projekt/1202868
